# Generated by Django 5.2.10 on 2026-02-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_users_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='USER',
            new_name='USERS',
        ),
    ]
