# Generated by Django 5.2.10 on 2026-02-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_user_complaint_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='logs',
            name='time',
            field=models.TimeField(),
        ),
    ]
