# Generated by Django 5.2.10 on 2026-01-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='image',
        ),
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
    ]
